# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11cKYoV78hlaZZkyCLGCd6rjO3sSd47YV
"""



"""
#1
name=input("Enter your name ")
age=input("Enter your age ")
print("Welcome ", name )
"""

"""
#2
n=input("Enter the value")
datatype=None
Float=None
word=None
for i in n:
  if(i=="." and word==True):
      word=True
  else:
    if((i >='A' and i<='Z')or (i >='a' and i<='z') ):
     word=True
    elif(i=="." and datatype=="int"):
     Float=True
    elif(int(i)>=0 and int(i)<=9):
      datatype="int"
if(word):
  print("string")
elif(Float):
  print("Float")
else:
  print("int")
"""

#2
n=input("Enter the value")
datatype=None
Float=None
word=None
for i in n:
  if(i=="." and word==True):
      word=True
  else:
    if((i >='A' and i<='Z')or (i >='a' and i<='z') ):
     word=True
    elif(i=="." and datatype=="int"):
     Float=True
    elif(int(i)>=0 and int(i)<=9):
      datatype="int"
if(word):
  print("string")
elif(Float):
  print("Float")
else:
  print("int")

#3

listt = ["apple", "banana", "cherry"]
print(listt)
listt.append("pineapple")
print(listt)
listt.remove("banana")
print(listt)
print(" In Uppercase")
for i in listt:
  print(f'{i.upper()} \t',end="")

#4
fruits = ("apple", "banana", "cherry")

(green, yellow, red) = fruits

print(f'{green}  {red}')

#5
students = {
  "Abd": "A",
  "Shaheer": "A",
  "Shah": "A",
  "Saqib":"F+",
  "Ali":"F+",
}
print(students)

#6

a = []

n = int(input("Enter the number of elements: "))

for i in range(n):
    element = input(f"Enter element {i+1}: ")
    a.append(element)

print("List:", a)



d = []

n = int(input("Enter the number of elements: "))

for i in range(n):
    element = input(f"Enter element {i+1}: ")
    d.append(element)

print("List:", d)


b=set(a)
c=set(d)
e=b.union(c)
print(f'Union {e}')

f = b.intersection(c)
print(f'Intersectionn {f}' )

#7
number = int(input("Please enter an integer: "))

if number > 0:
    sign = "positive"
elif number < 0:
    sign = "negative"
else:
    sign = "zero"

if number % 2 == 0:
    parity = "even"
else:
    parity = "odd"

print(f"The number {number} is {sign} and {parity}.")

#8
for i in range(1, 51):
    if i % 3 == 0 and i % 5 == 0:
        print("FizzBuzz")
    elif i % 3 == 0:
        print("Fizz")
    elif i % 5 == 0:
        print("Buzz")
    else:
        print(i)

#9
def factorial(n):
    if n < 0:
        return "Factorial is not defined for negative numbers."
    result = 1
    for i in range(1, n + 1):
        result *= i
    return result
n=int(input("Enter"))
factorial(n)

#10
def prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

user_input = int(input("Enter a number to check if it is prime or not: "))

if prime(user_input):
    print(f"{user_input}  prime number.")
else:
    print(f"{user_input}  not a prime number.")

#11
def square_numbers(numbers):
    squared_list = []
    for x in numbers:
        squared_list.append(x ** 2)
    return squared_list

input_list = [1, 2, 3, 4, 5]
squared_list = square_numbers(input_list)
print(squared_list)

#12
def merge(dict1, dict2):
    merged_dict = dict1.copy()
    merged_dict.update(dict2)
    return merged_dict

dict1 = {'a': 6, 'b': 5}
dict2 = {'b': 9, 'c': 8}
result = merge(dict1, dict2)
print(result)

#13
def remove_dup(nums):
    seen = set()
    res = []
    for n in nums:
        if n not in seen:
            seen.add(n)
            res.append(n)
    return res

nums = [1, 2, 3, 4, 4, 5]
result = remove_dup(nums)
print(result)

#14
is_palindrome = lambda s: (cleaned := ''.join(c.lower() for c in s if c.isalnum())) == cleaned[::-1]

print(is_palindrome("AaaA"))
print(is_palindrome("Hello World"))

#15
def fibonacci(n):
    fib = []
    x, y = 0, 1
    for i in range(n):
        fib.append(x)
        x, y = y, x + y
    return fib

n = int(input("Enter the number of Fibonacci numbers to generate: "))
print(fibonacci(n))

#16
def get_average():
    nums = []

    while True:
        val = input("Enter a number (or type 'done' to finish): ")

        if val.lower() == 'done':
            break

        try:
            num = float(val)
            nums.append(num)
        except ValueError:
            print("Invalid input. Please enter a valid number.")

    if nums:
        avg = sum(nums) / len(nums)
        print(f"The average is: {avg}")
    else:
        print("No numbers were entered.")

get_average()

#17
for i in range(1, 11):
    for j in range(1, 11):
        print(f"   {i * j}   ", end=' ')
    print()

#18
def register(users):
    name = input("Enter a username: ")
    if name in users:
        print("Username already taken. Try another.")
        return
    pwd = input("Enter a password: ")
    users[name] = pwd
    print("You are registered!")

def login(users):
    name = input("Enter your username: ")
    pwd = input("Enter your password: ")
    if name in users and users[name] == pwd:
        print("Login successful!")
    else:
        print("Wrong username or password.")

def main():
    users = {}

    while True:
        print("\nChoose an option:")
        print("1. Login")
        print("2. Register")
        print("3. Exit")

        choice = input("Enter your choice (1, 2, or 3): ")

        if choice == '1':
            login(users)
        elif choice == '2':
            register(users)
        elif choice == '3':
            break
        else:
            print("Invalid option. Try again.")

main()

#19
def count_words():
    s = input("Enter words separated by spaces: ").split()
    d = {}

    for w in s:
        if w in d:
            d[w] += 1
        else:
            d[w] = 1

    return d

result = count_words()
print("Word frequency:")
for k, v in result.items():
    print(f"{k}: {v}")

#20
def convert_temp():
    choice = input("Type 'C' to convert Celsius to Fahrenheit or 'F' to convert Fahrenheit to Celsius: ").upper()

    if choice == 'C':
        celsius = float(input("Enter temperature in Celsius: "))
        fahrenheit = (celsius * 9/5) + 32
        print(f"{celsius}°C is {fahrenheit}°F")

    elif choice == 'F':
        fahrenheit = float(input("Enter temperature in Fahrenheit: "))
        celsius = (fahrenheit - 32) * 5/9
        print(f"{fahrenheit}°F is {celsius}°C")

    else:
        print("Invalid choice. Please type 'C' or 'F'.")

convert_temp()