# -*- coding: utf-8 -*-
"""l217990.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U8acVLjn8Xzz6E4_OXsUUM7x48ELTD9X
"""

def identify_data_type(user_input):
    try:
        int_value = int(user_input)
        print(f"Data Type: Integer, Value: {int_value}")
    except ValueError:
        try:
            float_value = float(user_input)
            print(f"Data Type: Float, Value: {float_value}")
        except ValueError:
            print(f"Data Type: String, Value: {user_input}")

user_input = input("Enter a value: ")
identify_data_type(user_input)

fruits = ["apple", "banana", "cherry"]
fruits.append("orange")
fruits.remove("banana")

for fruit in fruits:
    print(fruit.upper())

my_tuple = (10, 20, 30, 40)
a, b, *_ = my_tuple
print("First:", a)
print("Second:", b)

name = input("Please enter your name: ")
age = input("Please enter your age: ")
print(f"Hello, {name}! You are {age} years old. Welcome!")

students = {
    "Ali": 85,
    "Ahmad": 90,
    "Sara": 78,
    "Zainab": 92,
    "Sadia": 88
}
print(students)

#will rewrite
list1 = list(map(int, input("Enter numbers for list 1: ").split()))
list2 = list(map(int, input("Enter numbers for list 2: ").split()))

set1, set2 = set(list1), set(list2)

print("Union:", set1 | set2)
print("Intersection:", set1 & set2)
print("Difference:", set1 - set2)

num = int(input("Enter an integer: "))

if num > 0:
    print("Positive")
elif num < 0:
    print("Negative")
else:
    print("Zero")

print("Even" if num % 2 == 0 else "Odd")

for i in range(1, 51):
    if i % 3 == 0 and i % 5 == 0:
        print("FizzBuzz")
    elif i % 3 == 0:
        print("Fizz")
    elif i % 5 == 0:
        print("Buzz")
    else:
        print(i)

def factorial(n):
    result = 1
    for i in range(1, n + 1):
        result *= i
    return result

num = int(input("Enter a non-negative integer: "))
print("Factorial:", factorial(num))

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True

num = int(input("Enter a number: "))
print("Prime" if is_prime(num) else "Not Prime")

def squares(nums):
    return [x**2 for x in nums]

numbers = list(map(int, input("Enter numbers: ").split()))
print(squares(numbers))

dict1 = {"a": 1, "b": 2, "c": 3}
dict2 = {"b": 20, "c": 30, "d": 40}

merged_dict = {**dict1, **dict2}
print(merged_dict)

def remove_duplicates(lst):
    seen = set()
    return [x for x in lst if not (x in seen or seen.add(x))]

numbers = list(map(int, input("Enter numbers: ").split()))
print(remove_duplicates(numbers))

def is_palindrome(s):
    normalized_string = ''.join(s.split()).lower()
    check_palindrome = lambda x: x == x[::-1]

    return check_palindrome(normalized_string)
input_string = input("Enter a string to check if it's a palindrome: ")

if is_palindrome(input_string):
    print(f'"{input_string}" is a palindrome.')
else:
    print(f'"{input_string}" is not a palindrome.')

def fibonacci(n):
    sequence = [0, 1]
    for _ in range(n - 2):
        sequence.append(sequence[-1] + sequence[-2])
    return sequence[:n]

num = int(input("Enter the number of Fibonacci terms: "))
print(fibonacci(num))

def calculate_average():
    numbers = []
    while True:
        num = input("Enter a number (or 'done' to finish): ")
        if num.lower() == "done":
            break
        try:
            numbers.append(float(num))
        except ValueError:
            print("Invalid input. Please enter a valid number.")

    if numbers:
        print("Average:", sum(numbers) / len(numbers))
    else:
        print("No numbers entered.")

calculate_average()

for i in range(1, 11):
    for j in range(1, 11):
        print(f"{i * j:4}", end=" ")
    print()

users = {}
def register():
    username = input("Enter username: ")
    password = input("Enter password: ")
    users[username] = password
    print("Registration successful!")
def login():
    username = input("Enter username: ")
    password = input("Enter password: ")
    if users.get(username) == password:
        print("Login successful!")
    else:
        print("Invalid credentials.")

register()
login()

words = input("Enter words: ").split()
word_count = {}

for word in words:
    word_count[word] = word_count.get(word, 0) + 1
print(word_count)

def convert_temperature():
    choice = input("Convert (C)elsius to Fahrenheit or (F)ahrenheit to Celsius? ").upper()
    temp = float(input("Enter temperature: "))

    if choice == "C":
        print("Fahrenheit:", (temp * 9/5) + 32)
    elif choice == "F":
        print("Celsius:", (temp - 32) * 5/9)
    else:
        print("Invalid choice")

convert_temperature()