# -*- coding: utf-8 -*-
"""lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vpNUpTZTtikcRBOXZcsLrnfnbaS_ldrj
"""

name=input

#task1
name=input("enter your name:")
age=int(input("enter your age"))
print("hello ",name)

#task2
data=int(input("enter your data"))
print(type(data))

#task3
cars=["civic","audi"]
print(cars)
cars.append("corolla")
print(cars)
cars.remove("corolla")
print(cars)
print([cars.upper() for cars in cars])

#task4
t=(1,2,3,4,5)
first,second=t[0],t[1]
print(first)
print(second)

#task5
st_grade={}

for i in range(5):
  name=input(f"enter name of student {i+1}:")
  grade=input(f"enter grade for {name}:")
  st_grade[name]=grade
  print(st_grade)

#task6

list1 = list(map(int, input("Enter the first list of integers separated by spaces: ").split()))
list2 = list(map(int, input("Enter the second list of integers separated by spaces: ").split()))


set1 = set(list1)
set2 = set(list2)


union_result = set1.union(set2)
intersection_result = set1.intersection(set2)
difference_result = set1.difference(set2)

print(f"Union of the sets: {union_result}")
print(f"Intersection of the sets: {intersection_result}")
print(f"Difference of the sets (set1 - set2): {difference_result}")

#task7

number = int(input("Enter an integer: "))


if number > 0:
    print("The number is positive.")
elif number < 0:
    print("The number is negative.")
else:
    print("The number is zero.")


if number % 2 == 0:
    print("The number is even.")
else:
    print("The number is odd.")

#task8
for number in range(1, 51):
    if number % 3 == 0 and number % 5 == 0:
        print("FizzBuzz")
    elif number % 3 == 0:
        print("Fizz")
    elif number % 5 == 0:
        print("Buzz")
    else:
        print(number)

#task9
def factorial(n):
    if n < 0:
        return "Factorial is not defined for negative numbers."
    result = 1
    for i in range(1, n + 1):
        result *= i
    return result


number = int(input("Enter a non-negative integer: "))

print(f"The factorial of {number} is: {factorial(number)}")

#task10

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

number = int(input("Enter a number to check if it is prime: "))

if is_prime(number):
    print(f"{number} is a prime number.")
else:
    print(f"{number} is not a prime number.")

#task11

def square_numbers(numbers):
    return [x**2 for x in numbers]

input_list = [1, 2, 3, 4, 5]
output_list = square_numbers(input_list)
print(f"Original list: {input_list}")
print(f"Squared list: {output_list}")

#task12

dict1 = {'a': 1, 'b': 2, 'c': 3}
dict2 = {'b': 20, 'd': 4}


merged_dict = dict1 | dict2


print("Merged dictionary:", merged_dict)

#task13

def remove_duplicates(input_list):
    return list(dict.fromkeys(input_list))


input_list = [1, 2, 2, 3, 4, 4, 5]
output_list = remove_duplicates(input_list)
print(f"List without duplicates: {output_list}")

#task14

is_palindrome = lambda s: (cleaned := ''.join(c.lower() for c in s if c.isalnum())) == cleaned[::-1]


test_string = "aabaa"
result = is_palindrome(test_string)
print(f"Is the string '{test_string}' a palindrome? {result}")

#task15
def fibonacci_sequence(n):
    if n <= 0:
        return []
    elif n == 1:
        return [0]
    elif n == 2:
        return [0, 1]
    else:
        sequence = [0, 1]
        for i in range(2, n):
            next_number = sequence[-1] + sequence[-2]
            sequence.append(next_number)
        return sequence

num_fibonacci = int(input("How many Fibonacci numbers do you want to generate? "))
result = fibonacci_sequence(num_fibonacci)
print(f"The first {num_fibonacci} Fibonacci numbers are: {', '.join(map(str, result))}")

#task16
def average_calculator():

    print("Enter numbers one by one. Type 'done' when you are finished.")
    numbers = []

    while True:
        user_input = input("Enter a number (or 'done' to finish): ").strip()

        if user_input.lower() == 'done':
            break

        try:
            number = float(user_input)
            numbers.append(number)
        except ValueError:
            print("Invalid input. Please enter a valid number.")

    if not numbers:
        print("No numbers were entered. Cannot calculate an average.")
        return


    average = sum(numbers) / len(numbers)
    print(f"The average of the entered numbers is: {average:.2f}")


average_calculator()

#task17
for row in range(1, 11):
    for column in range(1, 11):
        print(f"{row}x{column}={row * column}", end="\t")
    print()

#task18
user_credentials = {}

def register():
    print("\n--- User Registration ---")
    username = input("Enter a username: ")
    if username in user_credentials:
        print("Username already exists. Please try a different username.")
    else:
        password = input("Enter a password: ")
        user_credentials[username] = password
        print("Registration successful!")

def login():
    print("\n--- User Login ---")
    username = input("Enter your username: ")
    if username in user_credentials:
        password = input("Enter your password: ")
        if user_credentials[username] == password:
            print("Login successful! Welcome back!")
        else:
            print("Incorrect password. Please try again.")
    else:
        print("Username not found. Please register first.")

def main():
    while True:
        print("\n--- Welcome to the User System ---")
        print("1. Register")
        print("2. Login")
        print("3. Exit")
        choice = input("Enter your choice (1/2/3): ")

        if choice == "1":
            register()
        elif choice == "2":
            login()
        elif choice == "3":
            print("Exiting the system. Goodbye!")
            break
        else:
            print("Invalid choice. Please try again.")
main()

#task19
words = input("Enter a list of words separated by spaces: ").split()


word_count = {}

for word in words:
    if word in word_count:
        word_count[word] += 1
    else:
        word_count[word] = 1

print("\nWord Frequencies:")
for word, count in word_count.items():
    print(f"{word}: {count}")

#task20
def convert_temperature():

    print("\n--- Temperature Converter ---")
    print("1. Convert Celsius to Fahrenheit")
    print("2. Convert Fahrenheit to Celsius")


    choice = input("Enter your choice (1/2): ")

    if choice == "1":

        celsius = float(input("Enter temperature in Celsius: "))
        fahrenheit = (celsius * 9/5) + 32
        print(f"{celsius}°C is equal to {fahrenheit}°F")
    elif choice == "2":

        fahrenheit = float(input("Enter temperature in Fahrenheit: "))
        celsius = (fahrenheit - 32) * 5/9
        print(f"{fahrenheit}°F is equal to {celsius}°C")
    else:
        print("Invalid choice. Please select 1 or 2.")


convert_temperature()