integer_no = int(input("Enter integer number: "))
print("Data type is: ", type(integer_no))
integer_no2 = int(input("Enter integer number: "))
conv_to_float = float(integer_no2)
print("Int converted to float")
print("Data type is: ", type(conv_to_float))