list = input("Enter Elements of set 1 space separated :").split()
list2 = input("Enter Elements of set 2 space separated :").split() 
set1 = set(list)
set2 = set(list2)
print(set1)
print(set2)
set3=set1.union(set2)
set4=set1.intersection(set2)
set5=set1.difference(set2)
print(set3)
print(set4)
print(set5)
